### ISSUE TITLE
Update config schema

### ISSUE THREAD

**Issue by shubham1172** [shubham1172/pocket#13]
- Bifurcate actions into run/copy
    - Copying is tricky after chrooting
- Use environment variables.

```yaml
copy
- src: src1
  dest: dest1
- src: src2
  dest: dest2
run
- command1 args...
- command2 args...
env
  key1: value1
  key2: value2
```
