### ISSUE TITLE
Yaml parser for configuration file

### ISSUE THREAD

**Issue by shubham1172** [shubham1172/pocket#2]
Create a yaml parser that can parse the following format:
```yaml
name: container_name
image: image_name
actions:
    - copy: 
        src: source
        dest: destination
    - run: command
    - copy:
        src: source
        dest: destination
limit:
    cpu: cpu%
    mem: mem in MB
expose: port_number
```
- create a config class to map the same
